services:
  back:
    image: vpbuyanov/constructor-ietm
    container_name: back-pd
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - back-data:/back/volume
      - ./dist/build:/dist/build
    networks:
      team.mpu-cloud:

  mongodb:
    image: 'bitnami/mongodb:4.0'
    container_name: mongodb
    volumes:
      - mongodb:/mongo/pd
    ports:
      - 27017:27017
    networks:
      team.mpu-cloud:

  front:
    image: vpbuyanov/front-pd
    container_name: front-pd
    restart: no
    ports:
      - "4200:4200"
    volumes:
      - front-data:/front-pd/volume
    networks:
      team.mpu-cloud:

volumes:
  front-data:
  back-data:
  mongodb:

networks:
  team.mpu-cloud: